package com.springinaction.hibernate.mapping;

// Generated May 4, 2013 10:21:31 PM by Hibernate Tools 3.4.0.CR1

/**
 * Spitter generated by hbm2java
 */
public class Spitter implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1925565735419483097L;
	private int id;
	private String username;
	private String password;
	private String fullname;

	public Spitter() {
	}

	public Spitter(int id, String username, String password) {
		this.id = id;
		this.username = username;
		this.password = password;
	}

	public Spitter(int id, String username, String password, String fullname) {
		this.id = id;
		this.username = username;
		this.password = password;
		this.fullname = fullname;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getFullname() {
		return this.fullname;
	}

	public void setFullname(String fullname) {
		this.fullname = fullname;
	}
	
	public String toString(){
		StringBuffer buffer = new StringBuffer();
		
		buffer.append("ID : ").append(id).append(",");
		buffer.append("USERNAME : ").append(username).append(",");
		buffer.append("PASSWORD : ").append(password).append(",");
		buffer.append("FULLANME : ").append(fullname);
		
		return buffer.toString();
	}

}
