package com.restfully.shop.domain;

// default package
// Generated May 6, 2013 4:39:46 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Invoice generated by hbm2java
 */
public class Invoice implements java.io.Serializable {

	private int id;
	private Customer customer;
	private BigDecimal total;
	private Set items = new HashSet(0);

	public Invoice() {
	}

	public Invoice(int id) {
		this.id = id;
	}

	public Invoice(int id, Customer customer, BigDecimal total, Set items) {
		this.id = id;
		this.customer = customer;
		this.total = total;
		this.items = items;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public BigDecimal getTotal() {
		return this.total;
	}

	public void setTotal(BigDecimal total) {
		this.total = total;
	}

	public Set getItems() {
		return this.items;
	}

	public void setItems(Set items) {
		this.items = items;
	}

}
