package com.restfully.shop.domain;

// default package
// Generated May 6, 2013 4:39:46 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * Item generated by hbm2java
 */
public class Item implements java.io.Serializable {

	private ItemId id;
	private Invoice invoice;
	private Product product;
	private Integer quantity;
	private BigDecimal cost;

	public Item() {
	}

	public Item(ItemId id, Invoice invoice) {
		this.id = id;
		this.invoice = invoice;
	}

	public Item(ItemId id, Invoice invoice, Product product, Integer quantity,
			BigDecimal cost) {
		this.id = id;
		this.invoice = invoice;
		this.product = product;
		this.quantity = quantity;
		this.cost = cost;
	}

	public ItemId getId() {
		return this.id;
	}

	public void setId(ItemId id) {
		this.id = id;
	}

	public Invoice getInvoice() {
		return this.invoice;
	}

	public void setInvoice(Invoice invoice) {
		this.invoice = invoice;
	}

	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	public BigDecimal getCost() {
		return this.cost;
	}

	public void setCost(BigDecimal cost) {
		this.cost = cost;
	}

}
