package com.restfully.shop.domain;

// default package
// Generated May 6, 2013 4:39:46 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1122711030120742971L;
	private int id;
	private String name;
	private BigDecimal price;
	private Set items = new HashSet(0);

	public Product() {
	}

	public Product(int id) {
		this.id = id;
	}

	public Product(int id, String name, BigDecimal price, Set items) {
		this.id = id;
		this.name = name;
		this.price = price;
		this.items = items;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	public Set getItems() {
		return this.items;
	}

	public void setItems(Set items) {
		this.items = items;
	}

}
