package com.restfully.shop.domain;

// default package
// Generated May 6, 2013 4:39:46 PM by Hibernate Tools 3.4.0.CR1

/**
 * Test generated by hbm2java
 */
public class Test implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7626856507554891043L;
	private Integer id;

	public Test() {
	}

	public Test(Integer id) {
		this.id = id;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

}
